### PR TITLE
Implement sss javascript wrapper using WASM

### PR DESCRIPTION
**Pull request by bakaoh**
Refs: #1 
Demo https://bakaoh.github.io/sss-wasm

- [x] Implement a javascript library that can call the sss C code though WASM
- [x] Make the implementation compatible with sss-node, should work with the same tests as in that repo
- [x] Works in all major browsers, mobile and desktop, as well as node.js

### CODE REVIEW

**Comment by christianlundkvist** [comment]
Looks nice! Would be cool if there were some regression tests that could be used to make sure we're getting the same values from this as from the original SSS library. This seems to not be possible though because of the randomness introduced below the exposed interfaces.

**Comment by christianlundkvist** [comment]
Also would be nice to have @dsprenkels take a look if he is able to. This library could then potentially be donated to his collection of various sss-bindings.

**Comment by bakaoh** [comment]
@oed --- i've just updated randombytes.c, i hope that will be clearer

@christianlundkvist --- i don't know how to do that T__T

**Comment by oed** [comment]
@bakaoh seems like https://dsprenkels.com/sss/ is down

**Comment by KamesCG** [comment]
Another project recently launched (EthBuenoAires) to do time-lock secret sharing, might also be interested in helping support this library?

Kimono
> Kimono relies on an algorithm called Shamir’s Secret Sharing, which makes it possible to create N fragments from a secret such that any K of the fragments can reconstruct the original secret. 

https://github.com/hillstreetlabs/kimono
https://medium.com/@pfh/kimono-trustless-secret-sharing-using-time-locks-on-ethereum-8e7e696494d

**Comment by dsprenkels** [comment]
@oed (cc @bakaoh). Thanks for the heads-up. I think this may be due to a nginx/node.js HTTP2 upgrade issue, which looks like it could take some time to solve.

If you expect that your demo will remain up, then I could change the sss-node README to point to http://bakaoh.com/sss-wasm/ demo instead. What'd you think?

**Comment by bakaoh** [comment]
@dsprenkels -- sure, it's a github static pages so it'll always up

**Comment by dsprenkels** [comment]
Awesome. Will do then. :)

**Pull request merged**
